# OpenAI Configuration
openai:
  api_key: ""  # Set your OpenAI API key here or use environment variable
  model: "gpt-4-turbo"
  temperature: 0.1
  max_tokens: 4000
  timeout: 60

# Optimization Settings
optimization:
  skill_weight: 0.4
  experience_weight: 0.3
  education_weight: 0.2
  summary_weight: 0.1
  max_summary_length: 200
  keyword_boost: 1.5
  relevance_threshold: 0.7
  max_experience_items: 8
  max_skill_items: 15

# Output Settings
output:
  default_format: "pdf"
  include_original: false
  template_style: "modern"
  font_size: 11
  line_spacing: 1.15
  margin: 0.75
  page_size: "A4"

# ATS Optimization
ats:
  enabled: true
  keyword_density: 0.02
  max_keyword_repetition: 3
  avoid_graphics: true
  use_standard_fonts: true
  simple_formatting: true

# Skill Mapping
skill_mapping:
  # Technical skills synonyms
  technical_synonyms:
    python: ["python", "py", "python3", "python 3"]
    javascript: ["javascript", "js", "ecmascript", "es6"]
    react: ["react", "reactjs", "react.js", "react native"]
    node: ["node.js", "nodejs", "node", "express"]
    aws: ["aws", "amazon web services", "ec2", "s3", "lambda"]
    docker: ["docker", "containerization", "kubernetes", "k8s"]
    sql: ["sql", "mysql", "postgresql", "database", "rdbms"]
    git: ["git", "github", "gitlab", "version control"]
    machine_learning: ["ml", "machine learning", "ai", "artificial intelligence"]
    data_science: ["data science", "analytics", "statistics", "data analysis"]

  # Industry-specific skills
  industry_skills:
    software_engineering:
      - "agile"
      - "scrum"
      - "tdd"
      - "bdd"
      - "ci/cd"
      - "microservices"
      - "rest api"
      - "graphql"
    data_science:
      - "pandas"
      - "numpy"
      - "matplotlib"
      - "seaborn"
      - "scikit-learn"
      - "tensorflow"
      - "pytorch"
      - "jupyter"
    devops:
      - "kubernetes"
      - "terraform"
      - "ansible"
      - "jenkins"
      - "gitlab ci"
      - "monitoring"
      - "logging"

# Experience Optimization
experience:
  achievement_verbs:
    - "developed"
    - "implemented"
    - "designed"
    - "architected"
    - "led"
    - "managed"
    - "optimized"
    - "increased"
    - "reduced"
    - "improved"
    - "delivered"
    - "launched"
    - "scaled"
    - "automated"
    - "integrated"

  impact_metrics:
    - "performance"
    - "efficiency"
    - "cost"
    - "time"
    - "users"
    - "revenue"
    - "accuracy"
    - "uptime"
    - "throughput"
    - "quality"

# Templates
templates:
  modern:
    font_family: "Arial"
    header_color: "#2c3e50"
    section_color: "#34495e"
    accent_color: "#3498db"
    line_spacing: 1.15
  
  professional:
    font_family: "Times New Roman"
    header_color: "#000000"
    section_color: "#333333"
    accent_color: "#666666"
    line_spacing: 1.2
  
  creative:
    font_family: "Calibri"
    header_color: "#1a237e"
    section_color: "#303f9f"
    accent_color: "#3f51b5"
    line_spacing: 1.1

# API Settings
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  cors_origins: ["*"]
  rate_limit: 100
  rate_limit_window: 3600

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "cv_writer.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# File Processing
file_processing:
  max_file_size: 10485760  # 10MB
  allowed_extensions: [".pdf", ".docx", ".doc", ".txt"]
  temp_directory: "/tmp/cv_writer"
  cleanup_interval: 3600  # 1 hour

# Security
security:
  api_key_required: true
  rate_limiting: true
  input_validation: true
  sanitize_input: true
  max_request_size: 10485760  # 10MB 